In [1]:
import numpy as np

In [2]:
# !pip install numpy

In [3]:
ls = list(range(10))

In [4]:
type(ls)

list

In [5]:
import array
x = array.array('i',ls)

In [6]:
x

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
var =np.array(ls)

In [9]:
#3x5
type(var)

numpy.ndarray

In [10]:
#ETL and EDA

In [13]:
np.array([3.14,4,2,3], dtype='float32')

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [15]:
np.array([range(i, i+4) for i in [2,5,8]])

array([[ 2,  3,  4,  5],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [17]:
#a matrix fill with zero
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [18]:
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.full((4,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

- bool
- int
 - int16
- uint32
-float

 - complex

# 

In [22]:
# 0,50,2

In [24]:
#3 S start stop and step
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [27]:
np.linspace(0,1,50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])