In [1]:
import numpy as np

In [2]:
# !pip install numpy

In [3]:
ls = list(range(10))

In [4]:
type(ls)

list

In [5]:
import array
x = array.array('i',ls)

In [6]:
x

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
var =np.array(ls)

In [9]:
#3x5
type(var)

numpy.ndarray

In [10]:
#ETL and EDA

In [13]:
np.array([3.14,4,2,3], dtype='float32')

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [15]:
np.array([range(i, i+4) for i in [2,5,8]])

array([[ 2,  3,  4,  5],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [17]:
#a matrix fill with zero
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [18]:
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])